# JPA 및 Hibernate 설정
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테이블이 없으면 생성하고, 변경사항이 있으면 업데이트
    show-sql: true  # 실행되는 SQL 쿼리를 로그로 출력
  properties:
    hibernate:
      format_sql: true  # 실행되는 SQL 쿼리를 보기 좋게 서식화

# Hibernate SQL 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug  # Hibernate가 생성한 SQL 쿼리를 디버그 수준으로 로깅
    org.hibernate.type: trace  # Hibernate 데이터 유형 추적 (선택 사항)
